export TERM='xterm-256color'
export ZSH=$HOME/.oh-my-zsh


### Conf POWERLEVEL9K
POWERLEVEL9K_MODE=nerd-fontconfig
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_beginning"
POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=true
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
POWERLEVEL9K_CONTEXT_TEMPLATE=%n
POWERLEVEL9K_VCS_HIDE_TAGS=false


### barrita
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0b4'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0b6'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0b5'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0b7'
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=''

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=%F{black}'\ue0b6'
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX=%F{green}'\uf155 '%F{pink}
#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F{black}\ue0b6%F{white}"
#POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{pink} "

### command_execution
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='black'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='blue'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

### time
POWERLEVEL9K_TIME_BACKGROUND="black"
POWERLEVEL9K_TIME_FOREGROUND="249"
#POWERLEVEL9K_TIME_FORMAT="\UF43A %D{%H:%M  \UF133  %d.%m.%y}"
POWERLEVEL9K_TIME_FORMAT="\UF43A %D{%H:%M}"

### Dev icons
POWERLEVEL9K_PYTHON_ICON='\Ue606'
POWERLEVEL9K_AWS_ICON='\ue7ad'
POWERLEVEL9K_AWS_EB_ICON='\uf1b5'
POWERLEVEL9K_GO_ICON='\ue626'
POWERLEVEL9K_SWIFT_ICON='\ue755'
POWERLEVEL9K_SYMFONY_ICON='\ue756'

### git icons
POWERLEVEL9K_VCS_TAG_ICON='\uf02b'
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON='\UE703'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\UE708' 
POWERLEVEL9K_VCS_GIT_GITLAB_ICON='\Uf296'
POWERLEVEL9K_VCS_GIT_ICON='\uE702'
POWERLEVEL9K_VCS_BOOKMARK_ICON='\UF005'
POWERLEVEL9K_VCS_BRANCH_ICON='\uf418'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\uf0ab'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\uf0aa'
POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON='\uf0a9'
POWERLEVEL9K_VCS_STAGED_ICON='\uf055'
POWERLEVEL9K_VCS_STASH_ICON='\uf057'
POWERLEVEL9K_VCS_COMMIT_ICON='\uf417'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\uf056'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\uf059'


### directories icons
POWERLEVEL9K_FOLDER_ICON='\uF07b'
POWERLEVEL9K_HOME_ICON='\uF015'
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_LOCK_ICON='\UF023'

### System icons
POWERLEVEL9K_DISK_ICON='\uf0a0'
POWERLEVEL9K_FREEBSD_ICON='\uf30e'
POWERLEVEL9K_ANDROID_ICON='\ue70e'
POWERLEVEL9K_APPLE_ICON='\uf179'
POWERLEVEL9K_LINUX_ICON="%F{red}\uf302%F{blue}" 
POWERLEVEL9K_LOAD_ICON='\u'f252
POWERLEVEL9K_RAM_ICON='\ue266'
POWERLEVEL9K_SERVER_ICON='\uf473'

### Segments
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context os_icon ssh root_indicator dir_writable dir vcs)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context ssh os_icon dir_writable dir  vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time  background_jobs_joined time disk_usage)


ZSH_THEME="powerlevel9k/powerlevel9k"
plugins=(git git-extras sudo colorize history history-substring-search zsh-completions zsh-history-substring-search zsh-autosuggestions zsh-syntax-highlighting zsh-syntax-highlighting-filetypes compleat)

source $ZSH/oh-my-zsh.sh
if [[ $TERMINIX_ID ]]; then
        source /etc/profile.d/vte.sh
fi

